name: Assign Author

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  assignAuthor:
    name: Assign author
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    if: ${{ github.actor != 'dependabot' }}
    steps:
      - name: Assign author
        uses: technote-space/assign-author@v1
